---
- hosts: localhost
  connection: local
  become: false
  tasks:
  - name: Spot Request Creation with more options
    amazon.aws.ec2_spot_instance:
      launch_specification:
        image_id: ami-0900fe555666598a2
        key_name: tuncay
        security_group_ids: sg-0c51ed3484432fe7f
        instance_type: t2.micro
        block_device_mappings:
          - device_name: /dev/sdb
            ebs:
              delete_on_termination: true
              volume_type: gp3
              volume_size: 5
  - name: Spot Request Termination
    amazon.aws.ec2_spot_instance:
        spot_instance_request_ids: ['sir-3xeyr2wn', 'sir-zhn6vjdq']
        state: absent
  - name: Terminate aws instance
    ec2_instance:
        state: 'absent'
        instance_ids: '*'
    